
<h1>Phiew example</h1>
<h2>Controller state</h2>

<p>
	Notice how the controller remembers the username between requests by adding 
	a random "statekey" in the URL. Removing the statekey from the URL reset the state.
</p>

<form action="" method="post">
	<input type="hidden" name="action" value="postForm" />
	<input type="hidden" name="stateKey" value="<?php echo $this->escape($this->stateKey) ?>" />
	<input type="hidden" name="stateInstance" value="<?php echo $this->escape($this->stateInstance) ?>" />
	<label>Username: <input type="text" name="username" value="<?php echo $this->escape($this->username) ?>" /></label>
	<label>Password: <input type="password" name="password" id="password" value="" /></label>
	<input type="submit" value="Log in" />
</form>

<p><strong><?php echo $this->escape($this->message) ?></strong></p>
